=== cpadridev/DAM/1 - DAM/Lenguaje de Marcas/Unidad 4/Ejercicio5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="matricula">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="personal">
                    <xs:element name="dni" type="xs:string" pattern="[0-9]{8}[a-zA-Z]{1}"/>
				    <xs:element name="nombre" type="xs:string"/>
				    <xs:element name="titulacion" type="xs:string"/>
				    <xs:element name="curso_academico" type="xs:string"/>
            <xs:element name="domicilios" type="tDomicilios">
                    <xs:attribute name="codPostal" type="xs:string" pattern="[0-9]{5}"/>
                    <xs:attribute name="tDomicilios" type="xsd:string" use="required"/>
                        <xs:element name="domicilio">
                    <xs:element name="nombre" type="xs:string"/>
						</xs:element>
                    </xs:element>
                </xs:element>
				<xs:element name="pago">
                    <xs:element name="tipo_matricula" type="xs:string"/>
                </xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== cpadridev/DAM/1 - DAM/Lenguaje de Marcas/Unidad 4/Ejercicio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<matricula xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Ejercicio5.xsd"> 
    <persona> 
        <dni>12345678M</dni> 
        <titulacion>Ingeniería Informática</titulacion> 
        <curso_academico>1997/1998</curso_academico> 
        <domicilios> 
            <domicilio tipo="familiar" codPostal="46022"> 
                <nombre>C/ Principal nº1</nombre> 
            </domicilio> 
            <domicilio tipo="habitual" codPostal="46023"> 
                <nombre>C/ Secundaria nº2</nombre> 
            </domicilio> 
        </domicilios> 
    </persona>
	<persona> 
        <nombre>Juan Martinez Nebot</nombre> 
        <titulacion>Ingeniería Informática</titulacion> 
        <curso_academico>1997/1998</curso_academico> 
        <domicilios> 
            <domicilio tipo="familiar" codPostal="46022"> 
                <nombre>C/ Principal nº13</nombre> 
            </domicilio> 
        </domicilios> 
    </persona>  
    <pago>
        <tipo_matricula>Matrícula Ordinaria</tipo_matricula>
    </pago>
</matricula>
