=== cpadridev/DAM/1 - DAM/Lenguaje de Marcas/Unidad 4/Ejercicio1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="nota" maxOccurs="2">
		<xs:complexType>
			<xs:all>
				<xs:element name="para" type="xs:string" maxLenght="25"/>
				<xs:element name="de" type="xs:string" maxLenght="25"/>
				<xs:element name="titulo" type="xs:string" maxLenght="25"/>
				<xs:element name="contenido" type="xs:string" maxLenght="25"/>
				<xs:element name="codigo" type="xs:string" pattern="[a-zA-Z]{1}, [0-9]{4}"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== cpadridev/DAM/1 - DAM/Lenguaje de Marcas/Unidad 4/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<nota xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Ejercicio1.xsd"> 
    <para>Pedro</para> 
    <de>Laura</de> 
    <titulo>Recordatorio</titulo> 
    <contenido>A las 7:00 pm en la puerta del teatro</contenido>
    <codigo>C2233</codigo> 
</nota>
<nota> 
    <para>Jaime</para>    
    <contenido>A las 8:00 pm en la puerta del teatro</contenido>
    <codigo>a1231</codigo>
    <de>Susana</de> 
    <titulo>Recordatorio</titulo> 
</nota>
