=== cpadridev/DAM/1 - DAM/Lenguaje de Marcas/Unidad 4/Ejercicio2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="person">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="full_name" type="xs:string"/>
				<xs:element name="child_name" type="xs:string" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== cpadridev/DAM/1 - DAM/Lenguaje de Marcas/Unidad 4/Ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Ejercicio2.xsd">
    <full_name>Hege Refsnes</full_name>
    <child_name>Cecilie</child_name>
</person>
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Ejercicio2.xsd">
    <full_name>Tove Refsnes</full_name>
    <child_name>Hege</child_name>
    <child_name>Stale</child_name>
    <child_name>Jim</child_name>
    <child_name>Borge</child_name>
</person>
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Ejercicio2.xsd">
  <full_name>Stale Refsnes</full_name>
  <child_name>Android</child_name>
</person>
