<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cartelera [

 <!ELEMENT cartelera (película)*>
 <!ELEMENT película (título, título_original?, nacionalidad, género, (clasificación | sin_clasificar), sinopsis, director, reparto, web?, cartel?) >
 <!ELEMENT título (#PCDATA)>
 <!ELEMENT título_original (#PCDATA)>
 <!ELEMENT nacionalidad (#PCDATA)>
 <!ELEMENT género (#PCDATA)>
 <!ELEMENT clasificación EMPTY>
 <!ELEMENT sin_clasificar EMPTY>
 <!ELEMENT sinopsis (#PCDATA)>
 <!ELEMENT director (#PCDATA)>
 <!ELEMENT reparto (actor)+>
 <!ELEMENT web (#PCDATA)>
 <!ELEMENT cartel (#PCDATA)>
 <!ELEMENT actor (#PCDATA)>

 <!ATTLIST película código ID #REQUIRED>
 <!ATTLIST película duración CDATA "">
 <!ATTLIST película año CDATA "2003">
 <!ATTLIST clasificación edad (8 | 12 | 16 | 18 | tp) #REQUIRED>
]>

<cartelera>

	<película código="p1" duración="152" año="2002">
		<título>AQUELLAS JUERGAS UNIVERSITARIAS</título>
		<título_original>Old School</título_original>
		<nacionalidad>Estados Unidos</nacionalidad>
		<género>Comedia</género>
		<clasificación edad="tp"/>
		<sinopsis> 
            Mitch, Frank y Beanie son tres amigos treintañeros cuyas vidas no son exactamente lo que esperaban
        </sinopsis>
		<director>Todd Philips</director>
		<reparto>
			<actor>Luke Wilson</actor>
			<actor>Will Farrel</actor>
			<actor>Vince Vaughn</actor>
		</reparto>
		<web>http://www.uip.es</web>
		<cartel>caratulas/Aquellas juergas.jpg</cartel>
	</película>

	<película código="p17" duración="06">
		<título>EL ORO DE MOSCÚ</título>
		<nacionalidad>España</nacionalidad>
		<género>Comedia</género>
		<sin_clasificar/>
		<sinopsis> 
            Por una extraña coincidencia del destino, alguien recibe una información extraconfidencial de un anciano en sus últimos segundos de vida
        </sinopsis>
		<director>Jesús Bonilla</director>
		<reparto>
			<actor>Jesús Bonilla</actor>
			<actor>Santiago Segura</actor>
			<actor>Alfredo Landa</actor>
			<actor>Concha Velasco</actor>
			<actor>Antonio Resines</actor>
			<actor>Gabino Diego, María Barranco</actor>
			<actor>María Barranco</actor>
		</reparto>
	</película>
	
</cartelera>